version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      #- npm test
      #- npm run coverage
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      #- aws s3 cp --recursive coverage/ s3://$WEBSITE_S3_BUCKET/test/coverage --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      #- aws s3 cp index.html s3://$WEBSITE_S3_BUCKET/test/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - aws cloudformation deploy --template-file template-export.yml --stack-name nef-serverless-codebuild-proto-2 --capabilities CAPABILITY_IAM

artifacts:
  type: zip
  files:
    - template-export.yml
